"""`sweep aggregate --format json` never overwrites the marked markdown artifact (#193).

`--out` defaults to `docs/benchmarks.md` for both formats, and #145's splice
(D-011) is on the markdown arm only. Measured on `main`: `sweep aggregate
--format json` with no `--out` took the committed 53-line file to 25 lines of
JSON at exit 0, deleting the no-fabricated-benchmarks disclosure and the
table markers.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from emb_shootout.cli import main
from emb_shootout.sweep import TABLE_BEGIN_MARKER

REPO = Path(__file__).resolve().parent.parent


def _workspace(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A scratch copy of the two inputs the default invocation reads/writes."""
    (tmp_path / "docs").mkdir()
    shutil.copy(REPO / "docs" / "benchmarks.md", tmp_path / "docs" / "benchmarks.md")
    shutil.copytree(REPO / "results", tmp_path / "results")
    monkeypatch.chdir(tmp_path)
    return tmp_path / "docs" / "benchmarks.md"


def test_the_committed_artifact_carries_the_marker() -> None:
    # The premise of every test below: the default destination is marked.
    assert TABLE_BEGIN_MARKER in (REPO / "docs" / "benchmarks.md").read_text(encoding="utf-8")


def test_default_out_json_is_refused_and_the_file_is_untouched(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    bench = _workspace(tmp_path, monkeypatch)
    before = bench.read_bytes()
    assert main(["sweep", "aggregate", "--format", "json"]) == 2
    assert bench.read_bytes() == before
    err = capsys.readouterr().err
    assert "refusing to write --format json over docs/benchmarks.md" in err
    assert "--out <path>.json" in err


def test_explicit_marked_out_json_is_refused(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    bench = _workspace(tmp_path, monkeypatch)
    before = bench.read_bytes()
    assert main(["sweep", "aggregate", "--format", "json", "--out", str(bench)]) == 2
    assert bench.read_bytes() == before


@pytest.mark.parametrize("existing", [None, "an old unmarked file\n"], ids=["new", "unmarked"])
def test_json_to_an_unmarked_destination_still_writes(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, existing: str | None
) -> None:
    _workspace(tmp_path, monkeypatch)
    out = tmp_path / "agg.json"
    if existing is not None:
        out.write_text(existing, encoding="utf-8")
    assert main(["sweep", "aggregate", "--format", "json", "--out", str(out)]) == 0
    assert json.loads(out.read_text(encoding="utf-8"))["results"]


def test_markdown_default_still_splices_and_keeps_the_prose(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    bench = _workspace(tmp_path, monkeypatch)
    before = bench.read_text(encoding="utf-8")
    assert main(["sweep", "aggregate"]) == 0
    # The committed artifact is regenerated by exactly this command, so a
    # splice over the committed results reproduces it.
    assert bench.read_text(encoding="utf-8") == before
