"""The reproducers absorb a dominated provider result (#197).

`notebooks/_verify.py` and `notebooks/reproduce.ipynb` both ended with
``assert len(frontier) == len(results)``. That is true only while no result is
dominated, i.e. only while `results/` holds the hash baseline alone. The README
says the notebook "re-runs unchanged and absorbs" real-provider JSONs; the
first dominated one failed both reproducers with ``AssertionError``, and
`test_verify_script_runs_end_to_end` with them.

These arms run each reproducer against a scratch tree whose `results/` holds
the committed baseline plus two provider rows: one on the frontier, one
dominated by it. The third arm holds the frontier check identical in both
files and in `notebooks/_build_notebook.py`, which generates the notebook. That
is what `_verify.py`'s docstring used to claim a
`test_notebook_in_sync_with_verify_py` did (no such test existed).
"""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "notebooks" / "reproduce.ipynb"
VERIFY_SCRIPT = ROOT / "notebooks" / "_verify.py"
BUILDER = ROOT / "notebooks" / "_build_notebook.py"

BEGIN = "# frontier-check:begin"
END = "# frontier-check:end"

# voyage ($0.06, 0.84) is cheaper AND better than openai-large ($0.13, 0.80), so
# the frontier is {hash, voyage} and openai-large is dominated.
DOMINATED = "openai/text-embedding-3-large"


def _scratch_tree(tmp_path: Path) -> Path:
    for sub in ("notebooks", "results", "docs"):
        shutil.copytree(ROOT / sub, tmp_path / sub)
    baseline = json.loads((ROOT / "results" / "hash.json").read_text(encoding="utf-8"))
    # Same n_corpus / n_queries as the baseline, so `require_comparable` passes.
    for stem, name, cost, recall5 in (
        ("voyage", "voyage/voyage-3", 0.06, 0.84),
        ("openai-large", DOMINATED, 0.13, 0.80),
    ):
        row = dict(baseline)
        row.update(
            embedder_name=name,
            cost_per_million_tokens=cost,
            recall_at_k={"1": 0.6, "5": recall5, "10": 0.9},
            ndcg_at_10=0.7,
        )
        (tmp_path / "results" / f"{stem}.json").write_text(json.dumps(row), encoding="utf-8")
    assert len(list((tmp_path / "results").glob("*.json"))) == 3
    return tmp_path


def test_verify_script_absorbs_a_dominated_result(tmp_path):
    tree = _scratch_tree(tmp_path)
    # Resolve `emb_shootout` to this checkout, not whatever an editable install
    # points at: the scratch tree has no package of its own.
    env = {**os.environ, "PYTHONPATH": str(ROOT)}
    result = subprocess.run(
        [sys.executable, str(tree / "notebooks" / "_verify.py")],
        capture_output=True,
        text=True,
        timeout=180,
        env=env,
        cwd=tree,
    )
    assert result.returncode == 0, (
        f"_verify.py exited {result.returncode}\n--- stdout ---\n{result.stdout}"
        f"\n--- stderr ---\n{result.stderr}"
    )
    assert "frontier size: 2 point(s)" in result.stdout
    assert f"dominated: [{DOMINATED!r}]" in result.stdout
    assert "All steps completed without error." in result.stdout


def _code_cells() -> list[str]:
    nb = json.loads(NOTEBOOK.read_text(encoding="utf-8"))
    return ["".join(c["source"]) for c in nb["cells"] if c["cell_type"] == "code"]


def test_notebook_frontier_cells_absorb_a_dominated_result(tmp_path, monkeypatch):
    tree = _scratch_tree(tmp_path)
    cells = _code_cells()
    # The imports/ROOT cell, the aggregate cell and the frontier cell. The
    # corpus/query/sweep cells are skipped: they do not read `results/`.
    wanted = [
        next(c for c in cells if "ROOT = Path.cwd()" in c),
        next(c for c in cells if "aggregate_markdown(results)" in c),
        next(c for c in cells if "pareto_frontier(results)" in c),
    ]
    monkeypatch.chdir(tree / "notebooks")
    monkeypatch.setattr(sys, "path", list(sys.path))  # the imports cell inserts ROOT
    ns: dict = {}
    for src in wanted:
        exec(compile(src, str(NOTEBOOK), "exec"), ns)  # noqa: S102
    assert ns["ROOT"] == tree.resolve()
    assert len(ns["results"]) == 3
    assert len(ns["frontier"]) == 2
    assert ns["dominated"] == [DOMINATED]


def _block(text: str) -> str:
    lines = text.splitlines()
    starts = [i for i, line in enumerate(lines) if line.strip().startswith(BEGIN)]
    ends = [i for i, line in enumerate(lines) if line.strip() == END]
    assert len(starts) == 1, starts
    assert len(ends) == 1, ends
    assert starts[0] < ends[0], (starts, ends)
    return textwrap.dedent("\n".join(lines[starts[0] : ends[0] + 1]))


def _builder_block() -> str:
    """The block as `notebooks/_build_notebook.py` would write it.

    The committed notebook is generated by that script, so a fix made only to
    the `.ipynb` is undone the next time someone runs the documented builder.
    `build()` returns the notebook dict without writing anything.
    """
    spec = importlib.util.spec_from_file_location("_build_notebook", BUILDER)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    cells = ["".join(c["source"]) for c in module.build()["cells"] if c["cell_type"] == "code"]
    return _block(next(c for c in cells if BEGIN in c))


def test_frontier_check_is_identical_in_notebook_builder_and_verify_script():
    script_block = _block(VERIFY_SCRIPT.read_text(encoding="utf-8"))
    notebook_block = _block(next(c for c in _code_cells() if BEGIN in c))
    assert script_block == notebook_block
    assert _builder_block() == script_block
    assert "assert frontier" in script_block
    asserts = [line for line in script_block.splitlines() if line.startswith("assert ")]
    assert asserts
    assert not any("len(frontier) == len(results)" in a for a in asserts)
